TOPDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

USE_JASMIN_SUBMODULE ?= 0

#UNAME = $(shell uname)
#ifeq ($(UNAME_S),Linux)
#endif
#ifeq ($(UNAME_S),Darwin)
#endif
#
#UNAME_P := $(shell uname -p)
#ifeq ($(UNAME_P),x86_64)
# GCC ?= gcc
#endif
#ifneq ($(filter %86,$(UNAME_P)),)
# GCC ?= gcc
#endif
#ifneq ($(filter arm%,$(UNAME_P)),)
# GCC ?= arch -x86_64 gcc
#endif

JPATH ?= -I Keccak=$(TOPDIR)src/amd64
JFLAGS ?= -arch x86-64
JECFLAGS ?= --arch x86-64 --array-model=old 
# --------------------------------------------------------------------
CC ?= clang-14
CFLAGS ?= -Wall -O3 -fomit-frame-pointer -fwrapv -fPIC -fPIE -mavx2
# --------------------------------------------------------------------

ifeq ($(USE_JASMIN_SUBMODULE),0)
  JASMINC ?= jasminc
  JASMINCT ?= jasmin-ct
  JASMIN2EC ?= jasmin2ec
else
  JASMINC ?= $(TOPDIR)submodules/jasmin/compiler/jasminc
  JASMINCT ?= $(TOPDIR)submodules/jasmin/compiler/jasmin-ct
  JASMIN2EC ?= $(TOPDIR)submodules/jasmin/compiler/jasmin2ec
endif

.PHONY: .env
.env:
	@echo "TOPDIR="$(TOPDIR)
	@echo "--------"
	@echo "JPATH="$(JPATH)
	@echo "JASMINC="$(JASMINC)
	@echo "JFLAGS="$(JFLAGS)
	@echo "JASMINCT="$(JASMINCT)
	@echo "JECFLAGS="$(JECFLAGS)
	@echo "--------"
	@echo "CC="$(JPATH)
	@echo "CFLAGS="$(JASMINC)

