TOPDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

USE_JASMIN_SUBMODULE ?= 0

UNAME   := $(shell uname)
UNAME_P := $(shell uname -p)

ifeq ($(UNAME_S),Linux)
 CC ?= clang
endif
ifeq ($(UNAME_S),Darwin)
endif

ifeq ($(UNAME_P),x86_64)
endif
ifneq ($(filter %86,$(UNAME_P)),)
endif
ifneq ($(filter arm%,$(UNAME_P)),)
 CC ?= arch -x86_64 gcc
endif
CFLAGS ?= -Wall -O3 -fomit-frame-pointer -fwrapv -fPIC -fPIE -mavx2


JPATH ?= -I Keccak=$(TOPDIR)src/amd64
JFLAGS ?= -arch x86-64
JCTFLAGS ?= --arch x86-64 
JECFLAGS ?= --arch x86-64 --array-model=old 
# --------------------------------------------------------------------
# --------------------------------------------------------------------

ifeq ($(USE_JASMIN_SUBMODULE),0)
  JASMINC ?= jasminc
  JASMINCT ?= jasmin-ct
  JASMIN2EC ?= jasmin2ec
else
  JASMINC ?= $(TOPDIR)submodules/jasmin/compiler/jasminc
  JASMINCT ?= $(TOPDIR)submodules/jasmin/compiler/jasmin-ct
  JASMIN2EC ?= $(TOPDIR)submodules/jasmin/compiler/jasmin2ec
endif

.PHONY: .env
.env:
	@echo "UNAME="$(UNAME)
	@echo "UNAME_P="$(UNAME_P)
	@echo "TOPDIR="$(TOPDIR)
	@echo "--------"
	@echo "CC="$(CC)
	@echo "CFLAGS="$(CFLAGS)
	@echo "--------"
	@echo "JPATH="$(JPATH)
	@echo "JASMINC="$(JASMINC)
	@echo "JFLAGS="$(JFLAGS)
	@echo "JASMINCT="$(JASMINCT)
	@echo "JCTFLAGS="$(JCTFLAGS)
	@echo "JASMIN2EC="$(JASMIN2EC)
	@echo "JECFLAGS="$(JECFLAGS)

